server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smart_cart_db?createDatabaseIfNotExist=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: reg.clothify@gmail.com
    password: wyds qhbr aiqx moja
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: your-very-secure-jwt-secret-key-32-chars-long
  expiration: 86400000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    display-request-duration: true
    persist-authorization: true
    try-it-out-enabled: true
    url: /api-docs
